POST http://localhost:3000/products
Content-Type: application/json

{
    "name":"nice product 3",
    "width": 5.70,
    "height": 0.30,
    "length": 20,
    "price": 100,
    "type": "normal"
}
// name, width, height, length, price, type


###
GET http://localhost:3000/products

###
GET http://localhost:3000/products/3