POST http://localhost:3000/movements
Content-Type: application/json

{
      "sourceId": 5,
    "transfers": [
    {
        "productId": 1,
        "quantity": 5000
    },
    {
        "productId": 2,
        "quantity": 20
    }
  ]
}