POST http://localhost:3000/warehouses
Content-Type: application/json

{
    "name": "warehouse #6",
    "address": "Bulgaria, Varna",
    "volumeLimit": 15000000,
    "type": "hazardous"
}

###
PATCH  http://localhost:3000/warehouses/3
Content-Type: application/json

{
    "name": "warehouse #2",
    "address": "Bulgaria, Sofia",
    "volumeLimit": 20000000,
    "type": "normal"
}

###
DELETE  http://localhost:3000/warehouses/7

###
GET http://localhost:3000/warehouses

###
GET http://localhost:3000/warehouses/2/prodInfo

# {
#   "warehouseId": 2,
#   "productsQuantity": {
#     "1": 923,
#     "2": 276
#   }
# }

# {
#   "statusCode": 404,
#   "message": "Warehouse with id 1 not found",
#   "error": "Not Found"
# }